FROM alpine:3.15.0
LABEL version="1.0.0" maintainer="anthony marais" os="ubuntu"

ENV CONTAINER_USER=anthony_marais
RUN useradd $CONTAINER_USER
CMD echo hello-alpine, I’m $CONTAINER_USER and this is a container from my first image



